# Generated by Django 4.0.1 on 2022-02-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_global_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_message', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.rooms')),
            ],
        ),
    ]
