# Generated by Django 4.0.1 on 2022-02-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_message',
            name='message_send_by',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
