# Generated by Django 4.0.1 on 2022-02-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_room_message_message_send_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inside_room',
            fields=[
            ],
            options={
                'ordering': ['room'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_one.room_message',),
        ),
    ]
